export enum DashboardRouter {
    HOME = '/dashboard',
    SERVICE = '/dashboard/service',
    REFUND = '/dashboard/refund',
    CASHFLOW = '/dashboard/cashflow',
    MYAUTOLIVE = '/dashboard/myautolive',
    PAYMENT_HISTORY = '/dashboard/payment/history',
    PLATFORM = '/dashboard/platform',
    CRON = '/dashboard/crond',
    ORDER = '/dashboard/order',
    USER = '/dashboard/user',
    VPS = '/dashboard/vps',
    LIVESTREAM = '/dashboard/live-management',
    ADVANDED_CONFIG = '/dashboard/advanced-config',
    ACCOUNT_SCRIPT = '/dashboard/account-script',
    SCRIPT_LIBRARY = '/dashboard/script_library',
    USER_PROFILE = '/dashboard/user/info',
    SETTING = '/dashboard/settings',
    PUBLICKEY = '/dashboard/publickey',
    VPS_CONFIG = '/dashboard/vps-config',
    SCRIPT_SETUP = '/dashboard/script-setup'
}
